/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			createRule: null,
			deleteRule: null,
			fields: [
				{
					autogeneratePattern: '[a-z0-9]{15}',
					hidden: false,
					id: 'text3208210256',
					max: 15,
					min: 15,
					name: 'id',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text1045914785',
					max: 0,
					min: 0,
					name: 'textBase',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: true,
					id: 'text1400748618',
					max: 0,
					min: 0,
					name: 'textHidden',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text3896072459',
					max: 0,
					min: 0,
					name: 'textNonempty',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: true,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text4229961895',
					max: 0,
					min: 5,
					name: 'textMin5',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text99023707',
					max: 10,
					min: 0,
					name: 'textMax10',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text2287149522',
					max: 10,
					min: 5,
					name: 'textMin5Max10',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '',
					hidden: false,
					id: 'text2159983458',
					max: 0,
					min: 0,
					name: 'textPattern',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '[a-z0-9]{30}',
					hidden: false,
					id: 'text1610787347',
					max: 0,
					min: 0,
					name: 'textAutoGen',
					pattern: '',
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: 'text',
				},
				{
					autogeneratePattern: '[a-z0-9]{10}',
					hidden: true,
					id: 'text211404613',
					max: 10,
					min: 5,
					name: 'textAll',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: false,
					required: true,
					system: false,
					type: 'text',
				},
			],
			id: 'pbc_4285667772',
			indexes: [],
			listRule: null,
			name: 'text',
			system: false,
			type: 'base',
			updateRule: null,
			viewRule: null,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId('pbc_4285667772')

		return app.delete(collection)
	}
)
