/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			createRule: null,
			deleteRule: null,
			fields: [
				{
					autogeneratePattern: '[a-z0-9]{15}',
					hidden: false,
					id: 'text3208210256',
					max: 15,
					min: 15,
					name: 'id',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: 'text',
				},
				{
					hidden: false,
					id: 'select2312776735',
					maxSelect: 1,
					name: 'selectSingleBase',
					presentable: false,
					required: false,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: false,
					id: 'select2956295411',
					maxSelect: 1,
					name: 'selectSingleNonempty',
					presentable: false,
					required: true,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: true,
					id: 'select1362904915',
					maxSelect: 1,
					name: 'selectSingleHidden',
					presentable: false,
					required: false,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: true,
					id: 'select1015890491',
					maxSelect: 1,
					name: 'selectSingleAll',
					presentable: false,
					required: true,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: false,
					id: 'select2907883598',
					maxSelect: 7,
					name: 'selectMultipleBase',
					presentable: false,
					required: false,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: false,
					id: 'select2721487578',
					maxSelect: 7,
					name: 'selectMultipleNonempty',
					presentable: false,
					required: true,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: true,
					id: 'select1442523567',
					maxSelect: 7,
					name: 'selectMultipleHidden',
					presentable: false,
					required: false,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
				{
					hidden: true,
					id: 'select13284808',
					maxSelect: 7,
					name: 'selectMultipleAll',
					presentable: false,
					required: true,
					system: false,
					type: 'select',
					values: ['a', 'b', 'c', "'", '"', '`', '\\'],
				},
			],
			id: 'pbc_2095159182',
			indexes: [],
			listRule: null,
			name: 'select',
			system: false,
			type: 'base',
			updateRule: null,
			viewRule: null,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId('pbc_2095159182')

		return app.delete(collection)
	}
)
