/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			createRule: null,
			deleteRule: null,
			fields: [
				{
					autogeneratePattern: '[a-z0-9]{15}',
					hidden: false,
					id: 'text3208210256',
					max: 15,
					min: 15,
					name: 'id',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: 'text',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation759077606',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleBase',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: true,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation3368592677',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleCascadeDelete',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation1629615717',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleNonempty',
					presentable: false,
					required: true,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: true,
					id: 'relation3057692666',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleHidden',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: true,
					collectionId: '_pb_users_auth_',
					hidden: true,
					id: 'relation167761501',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleAll',
					presentable: false,
					required: true,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation2394886192',
					maxSelect: 1,
					minSelect: 0,
					name: 'relationSingleUnique',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation2448616542',
					maxSelect: 999,
					minSelect: 0,
					name: 'relationMultipleBase',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation2287557857',
					maxSelect: 999,
					minSelect: 5,
					name: 'relationMultipleMin5',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: true,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation3937064997',
					maxSelect: 999,
					minSelect: 0,
					name: 'relationMultipleCascadeDelete',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation2285898860',
					maxSelect: 999,
					minSelect: 0,
					name: 'relationMultipleNonempty',
					presentable: false,
					required: true,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: true,
					id: 'relation2230297401',
					maxSelect: 999,
					minSelect: 0,
					name: 'relationMultipleHidden',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: true,
					collectionId: '_pb_users_auth_',
					hidden: true,
					id: 'relation3289324486',
					maxSelect: 999,
					minSelect: 5,
					name: 'relationMultipleAll',
					presentable: false,
					required: true,
					system: false,
					type: 'relation',
				},
				{
					cascadeDelete: false,
					collectionId: '_pb_users_auth_',
					hidden: false,
					id: 'relation3155172595',
					maxSelect: 999,
					minSelect: 0,
					name: 'relationMultipleUnique',
					presentable: false,
					required: false,
					system: false,
					type: 'relation',
				},
			],
			id: 'pbc_583475024',
			indexes: [
				'CREATE UNIQUE INDEX `idx_Si14UW6Aj6` ON `rr` (`relationSingleUnique`)',
				'CREATE UNIQUE INDEX `idx_2pz0DQ72F6` ON `rr` (`relationMultipleUnique`)',
			],
			listRule: null,
			name: 'relation',
			system: false,
			type: 'base',
			updateRule: null,
			viewRule: null,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId('pbc_583475024')

		return app.delete(collection)
	}
)
