/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			createRule: null,
			deleteRule: null,
			fields: [
				{
					autogeneratePattern: '[a-z0-9]{15}',
					hidden: false,
					id: 'text3208210256',
					max: 15,
					min: 15,
					name: 'id',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: 'text',
				},
				{
					hidden: false,
					id: 'file1722549524',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileSingleBase',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file3795270806',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [
						'image/jpeg',
						'image/png',
						'image/svg+xml',
						'image/gif',
						'image/webp',
					],
					name: 'fileSingleMimeTypes',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file1079707061',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [],
					name: 'singleThumbsixze',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: ['50x50'],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file2488106726',
					maxSelect: 1,
					maxSize: 100,
					mimeTypes: [],
					name: 'fileSingleMaxFileSize',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file1542800728',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileSingleProtected',
					presentable: false,
					protected: true,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file2134807182',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileSingleNonempty',
					presentable: false,
					protected: false,
					required: true,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file137994776',
					maxSelect: 1,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileSingleHidden',
					presentable: false,
					protected: false,
					required: true,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: true,
					id: 'file2522691515',
					maxSelect: 1,
					maxSize: 100,
					mimeTypes: [
						'image/jpeg',
						'image/png',
						'image/svg+xml',
						'image/gif',
						'image/webp',
					],
					name: 'fileSingleAll',
					presentable: false,
					protected: true,
					required: true,
					system: false,
					thumbs: ['50x50'],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file202663583',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileMultipleBase',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file1506658685',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [
						'image/jpeg',
						'image/png',
						'image/svg+xml',
						'image/gif',
						'image/webp',
					],
					name: 'fileMultipleMimeTypes',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file1561049514',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileMultipleThumbSize',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: ['50x50'],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file3582085524',
					maxSelect: 99,
					maxSize: 100,
					mimeTypes: [],
					name: 'fileMultipleMaxFileSize',
					presentable: false,
					protected: false,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file3863183116',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileMultipleProtected',
					presentable: false,
					protected: true,
					required: false,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file427337476',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileMultipleNonempty',
					presentable: false,
					protected: false,
					required: true,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: false,
					id: 'file4034587010',
					maxSelect: 99,
					maxSize: 0,
					mimeTypes: [],
					name: 'fileMultipleHidden',
					presentable: false,
					protected: false,
					required: true,
					system: false,
					thumbs: [],
					type: 'file',
				},
				{
					hidden: true,
					id: 'file2679399288',
					maxSelect: 99,
					maxSize: 100,
					mimeTypes: [
						'image/jpeg',
						'image/png',
						'image/svg+xml',
						'image/gif',
						'image/webp',
					],
					name: 'fileMultipleAll',
					presentable: false,
					protected: true,
					required: true,
					system: false,
					thumbs: ['50x50'],
					type: 'file',
				},
			],
			id: 'pbc_2878493088',
			indexes: [],
			listRule: null,
			name: 'file',
			system: false,
			type: 'base',
			updateRule: null,
			viewRule: null,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId('pbc_2878493088')

		return app.delete(collection)
	}
)
