/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			createRule: null,
			deleteRule: null,
			fields: [
				{
					autogeneratePattern: '[a-z0-9]{15}',
					hidden: false,
					id: 'text3208210256',
					max: 15,
					min: 15,
					name: 'id',
					pattern: '^[a-z0-9]+$',
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: 'text',
				},
				{
					hidden: false,
					id: 'number1539215756',
					max: null,
					min: null,
					name: 'numberBase',
					onlyInt: false,
					presentable: false,
					required: false,
					system: false,
					type: 'number',
				},
				{
					hidden: false,
					id: 'number2580147594',
					max: null,
					min: 5,
					name: 'numberMin5',
					onlyInt: false,
					presentable: false,
					required: false,
					system: false,
					type: 'number',
				},
				{
					hidden: false,
					id: 'number1079791323',
					max: 10,
					min: null,
					name: 'numberMax10',
					onlyInt: false,
					presentable: false,
					required: false,
					system: false,
					type: 'number',
				},
				{
					hidden: false,
					id: 'number2958389237',
					max: null,
					min: null,
					name: 'numberNonzero',
					onlyInt: false,
					presentable: false,
					required: true,
					system: false,
					type: 'number',
				},
				{
					hidden: true,
					id: 'number3196093407',
					max: null,
					min: null,
					name: 'numberHidden',
					onlyInt: false,
					presentable: false,
					required: false,
					system: false,
					type: 'number',
				},
				{
					hidden: false,
					id: 'number1849360396',
					max: null,
					min: null,
					name: 'numberNoDecimals',
					onlyInt: true,
					presentable: false,
					required: false,
					system: false,
					type: 'number',
				},
				{
					hidden: true,
					id: 'number1437936669',
					max: 10,
					min: 5,
					name: 'numberAll',
					onlyInt: true,
					presentable: false,
					required: true,
					system: false,
					type: 'number',
				},
			],
			id: 'pbc_2709742106',
			indexes: [],
			listRule: null,
			name: 'number',
			system: false,
			type: 'base',
			updateRule: null,
			viewRule: null,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId('pbc_2709742106')

		return app.delete(collection)
	}
)
